const GAMES = [
  {
    id: 'zombie-slayer',
    title: 'Zombie Slayer',
    slug: 'zombie-slayer',
    tagline: 'Survive the dark forest. Slay the Boss.',
    description: 'A top-down action survival game. Fight waves of zombies, loot treasure chests and defeat the Boss to win.',
    longDescription: 'Zombie Slayer drops you into a dark forest teeming with the undead. Survive wave after wave of zombies, search for hidden treasure chests to unlock powerful upgrades, and fight your way to the Boss. Only the most skilled survivors will claim the legendary Rei Sword and live to tell the tale.',
    thumbnail: '/zombie-slayer/thumb.png',
    ogImage: '/zombie-slayer/og.png',
    category: 'action',
    difficulty: 'medium', // easy | medium | hard
    status: 'live', // live | coming-soon
    releaseDate: '2026-06',
    version: '0.4',
    controls: {
      keyboard: ['WASD — Move', 'Mouse — Aim', 'Click — Attack', 'SPACE / E — Open Chest'],
      touch: ['Left joystick — Move', 'Tap right — Attack', 'Tap chest button — Open Chest'],
    },
    tags: ['action', 'survival', 'horror', 'zombies'],
    seo: {
      title: 'Zombie Slayer — REI Games Studio',
      description: 'Survive waves of zombies in a dark forest. Loot chests, find the Rei Sword, and defeat the Boss. Free browser game by REI Games Studio.',
      canonical: 'https://reis.games/zombie-slayer/',
    },
    related: ['turbo-pixel', 'dungeon-rei'],
  },
  {
    id: 'turbo-pixel',
    title: 'Turbo Pixel',
    slug: 'turbo-pixel',
    tagline: 'Coming Soon',
    description: 'A high-speed pixel racing game.',
    longDescription: '',
    thumbnail: '/images/coming-soon-turbo.png',
    ogImage: '',
    category: 'racing',
    difficulty: 'easy',
    status: 'coming-soon',
    releaseDate: null,
    version: null,
    controls: { keyboard: [], touch: [] },
    tags: ['racing', 'pixel'],
    seo: { title: 'Turbo Pixel — REI Games Studio', description: 'A high-speed pixel racing game. Coming soon to reis.games.', canonical: 'https://reis.games/turbo-pixel/' },
    related: ['zombie-slayer', 'dungeon-rei'],
  },
  {
    id: 'dungeon-rei',
    title: 'Dungeon REI',
    slug: 'dungeon-rei',
    tagline: 'Coming Soon',
    description: 'Explore procedurally generated dungeons.',
    longDescription: '',
    thumbnail: '/images/coming-soon-dungeon.png',
    ogImage: '',
    category: 'rpg',
    difficulty: 'hard',
    status: 'coming-soon',
    releaseDate: null,
    version: null,
    controls: { keyboard: [], touch: [] },
    tags: ['rpg', 'dungeon', 'adventure'],
    seo: { title: 'Dungeon REI — REI Games Studio', description: 'Explore procedurally generated dungeons. Coming soon to reis.games.', canonical: 'https://reis.games/dungeon-rei/' },
    related: ['zombie-slayer', 'space-pixel'],
  },
  {
    id: 'space-pixel',
    title: 'Space Pixel',
    slug: 'space-pixel',
    tagline: 'Coming Soon',
    description: 'A pixel space shooter with retro vibes.',
    longDescription: '',
    thumbnail: '/images/coming-soon-space.png',
    ogImage: '',
    category: 'shooter',
    difficulty: 'medium',
    status: 'coming-soon',
    releaseDate: null,
    version: null,
    controls: { keyboard: [], touch: [] },
    tags: ['shooter', 'space', 'pixel'],
    seo: { title: 'Space Pixel — REI Games Studio', description: 'Retro space shooter. Coming soon to reis.games.', canonical: 'https://reis.games/space-pixel/' },
    related: ['zombie-slayer', 'turbo-pixel'],
  },
];

if (typeof module !== 'undefined') module.exports = GAMES;
